node('maven') {
  stage('Build') {
    sh "cat /tmp/artifacts/configuration/settings.xml"
    git branch: 'master', url: 'https://github.com/nalbam/sample-spring'
    sh "mvn clean package -DskipTests=true"
  }
  stage('Unit Tests') {
    sh "mvn test"
    step([$class: 'JUnitResultArchiver', testResults: '**/target/surefire-reports/TEST-*.xml'])
  }
  stage('Code Analysis') {
    sh "mvn sonar:sonar -Dsonar.host.url=http://sonarqube.ops.svc:9000 -DskipTests=true"
  }
  stage('Build Image') {
    openshiftBuild(namespace: 'ops', buildConfig: 'sample-spring', showBuildLogs: 'true')
  }
  stage('Deploy DEV') {
    openshiftTag(namespace: 'ops', sourceStream: 'sample-spring', sourceTag: 'latest', destinationNamespace: 'dev', destinationStream: 'sample-spring', destinationTag: 'latest')
    openshiftDeploy(namespace: 'dev', deploymentConfig: 'sample-spring')
    openshiftScale(namespace: 'dev', deploymentConfig: 'sample-spring', replicaCount: '2')
  }
  stage('Proceeed QA') {
    input 'Proceeed ?'
  }
  stage('Deploy QA') {
    openshiftTag(namespace: 'ops', sourceStream: 'sample-spring', sourceTag: 'latest', destinationNamespace: 'qa', destinationStream: 'sample-spring', destinationTag: 'latest')
    openshiftDeploy(namespace: 'qa', deploymentConfig: 'sample-spring')
    openshiftScale(namespace: 'qa', deploymentConfig: 'sample-spring', replicaCount: '2')
  }
}
