node('maven') {
  stage 'build'
    openshiftBuild(namespace: 'dev', buildConfig: 'sample-spring', showBuildLogs: 'true')
  stage 'deploy DEV'
    openshiftDeploy(namespace: 'dev', deploymentConfig: 'sample-spring')
    openshiftScale(namespace: 'dev', deploymentConfig: 'sample-spring', replicaCount: '2')
  stage 'deploy QA'
    input 'Proceeed ?'
    openshiftTag(namespace: 'dev', sourceStream: 'sample-spring', sourceTag: 'latest', destinationNamespace: 'qa', destinationStream: 'sample-spring', destinationTag: 'latest')
    openshiftDeploy(namespace: 'qa', deploymentConfig: 'sample-spring')
    openshiftScale(namespace: 'qa', deploymentConfig: 'sample-spring', replicaCount: '2')
}
