name: build

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "1.8"
          java-package: jdk
          architecture: x64

      - name: Run Build
        run: |
          ./build.sh

      - name: Bump Version
        uses: opspresso/action-builder@master
        with:
          args: --version

      - name: Release to GitHub
        uses: opspresso/action-builder@master
        with:
          args: --release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger for GitOps
        uses: opspresso/action-builder@master
        with:
          args: --dispatch
        env:
          GITHUB_TOKEN: ${{ secrets.GHP_TOKEN }}
          GITOPS_REPO: "opspresso/argocd-env-demo"
          PROJECT: ${{ github.event.repository.name }}

      - name: Build & Push to Docker Hub
        uses: opspresso/action-builder@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          # TAG_NAME: ${{ github.ref }}
          # PLATFORM: "linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6"
          BUILDX: "true"
          # LATEST: "true"

      - name: Build & Push to AWS ECR Private
        uses: opspresso/action-builder@master
        with:
          args: --ecr
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_BRUCE }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_BRUCE }}
          AWS_REGION: "ap-northeast-2"
          # REGISTRY: "public.ecr.aws/nalbam"
          # TAG_NAME: ${{ github.ref }}
          # PLATFORM: "linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6"
          BUILDX: "true"
          # LATEST: "true"

      # - name: Build & Push to AWS ECR Public
      #   uses: opspresso/action-builder@master
      #   with:
      #     args: --ecr
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: "ap-northeast-2"
      #     REGISTRY: "public.ecr.aws/nalbam"
      #     # TAG_NAME: ${{ github.ref }}
      #     # PLATFORM: "linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6"
      #     BUILDX: "true"
      #     # LATEST: "true"

      # - name: Build & Push to Quay.io
      #   uses: opspresso/action-builder@master
      #   with:
      #     args: --docker
      #   env:
      #     USERNAME: ${{ secrets.QUAY_USERNAME }}
      #     PASSWORD: ${{ secrets.QUAY_PASSWORD }}
      #     REGISTRY: "quay.io"
      #     # TAG_NAME: ${{ github.ref }}
      #     # PLATFORM: "linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6"
      #     BUILDX: "true"
      #     # LATEST: "true"

      # - name: Build & Push to GitHub Package
      #   uses: opspresso/action-builder@master
      #   with:
      #     args: --docker
      #   env:
      #     PASSWORD: ${{ secrets.GHP_TOKEN }}
      #     REGISTRY: "docker.pkg.github.com"
      #     # TAG_NAME: ${{ github.ref }}
      #     # PLATFORM: "linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6"
      #     # BUILDX: "true"
      #     # LATEST: "true"
