name: build

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "1.8"
          java-package: jdk
          architecture: x64

      - name: Run Build
        run: |
          ./build.sh

      - name: Bump Version
        uses: opspresso/action-builder@master
        with:
          args: --version

      - name: Release to GitHub
        uses: opspresso/action-builder@master
        with:
          args: --release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger for GitOps
        uses: opspresso/action-builder@master
        with:
          args: --dispatch
        env:
          GITHUB_TOKEN: ${{ secrets.GHP_TOKEN }}
          GITOPS_REPO: "opspresso/argocd-env-demo"
          PROJECT: ${{ github.event.repository.name }}

      - name: Prepare
        id: prep
        run: |
          DOCKERHUB_IMAGE=nalbam/${{ github.event.repository.name }}
          VERSION=$(git describe --abbrev=0 --tags)
          TAGS="${DOCKERHUB_IMAGE}:${VERSION},${DOCKERHUB_IMAGE}:latest"
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=dockerhub_image::${DOCKERHUB_IMAGE}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Login to Github Container Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.prep.outputs.tags }}
          labels: org.opencontainers.image.version=${{ steps.prep.outputs.version }}

      # - name: Build & Push to Docker Hub
      #   uses: opspresso/action-docker@master
      #   with:
      #     args: --docker
      #   env:
      #     USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      #     # TAG_NAME: ${{ github.ref }}
      #     # PLATFORM: "linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6"
      #     # BUILDX: "true"
      #     # LATEST: "true"

      # - name: Build & Push to AWS ECR Private
      #   uses: opspresso/action-docker@master
      #   with:
      #     args: --ecr
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_BRUCE }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_BRUCE }}
      #     AWS_REGION: "ap-northeast-2"
      #     # REGISTRY: "public.ecr.aws/nalbam"
      #     # TAG_NAME: ${{ github.ref }}
      #     # PLATFORM: "linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6"
      #     # BUILDX: "true"
      #     # LATEST: "true"

      # - name: Build & Push to AWS ECR Public
      #   uses: opspresso/action-docker@master
      #   with:
      #     args: --ecr
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: "ap-northeast-2"
      #     REGISTRY: "public.ecr.aws/nalbam"
      #     # TAG_NAME: ${{ github.ref }}
      #     # PLATFORM: "linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6"
      #     BUILDX: "true"
      #     # LATEST: "true"

      # - name: Build & Push to Quay.io
      #   uses: opspresso/action-docker@master
      #   with:
      #     args: --docker
      #   env:
      #     USERNAME: ${{ secrets.QUAY_USERNAME }}
      #     PASSWORD: ${{ secrets.QUAY_PASSWORD }}
      #     REGISTRY: "quay.io"
      #     # TAG_NAME: ${{ github.ref }}
      #     # PLATFORM: "linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6"
      #     BUILDX: "true"
      #     # LATEST: "true"

      # - name: Build & Push to GitHub Package
      #   uses: opspresso/action-docker@master
      #   with:
      #     args: --docker
      #   env:
      #     PASSWORD: ${{ secrets.GHP_TOKEN }}
      #     REGISTRY: "docker.pkg.github.com"
      #     # TAG_NAME: ${{ github.ref }}
      #     # PLATFORM: "linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6"
      #     # BUILDX: "true"
      #     # LATEST: "true"
