name: Build-Tag

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "1.8"
          java-package: jdk
          architecture: x64

      - name: Run Build
        run: |
          ./build.sh

      # - name: Trigger for GitOps
      #   uses: opspresso/action-builder@master
      #   with:
      #     args: --dispatch
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     GITOPS_REPO: "nalbam/argocd-env-demo"
      #     EVENT_TYPE: "build"
      #     TARGET_ID: ${{ github.event.repository.name }}

      # - name: Build & Push to Docker Hub
      #   uses: opspresso/action-builder@master
      #   with:
      #     args: --docker
      #   env:
      #     # USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      #     TAG_NAME: ${{ github.ref }}
      #     LATEST: "true"

      - name: Build & Push to GitHub Package
        uses: opspresso/action-builder@master
        with:
          args: --docker
        env:
          # USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.GITHUB_PERSONAL_TOKEN }}
          REGISTRY: "docker.pkg.github.com"
          TAG_NAME: ${{ github.ref }}

      - name: Build & Push to AWS ECR
        uses: opspresso/action-builder@master
        with:
          args: --ecr
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-northeast-2"
          TAG_NAME: ${{ github.ref }}
          LATEST: "true"
